# action.yaml
name: 'GitHub Action Checkbox Checker'
description: 'GitHub Action that checks when a PR is merged and edits comments referring to it'
inputs:
  pat:
    description: 'GitHub Personal Access Token to edit comments'
    required: true
  merging_pr_number:
    description: 'Number of the PR being merged'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "PAT=${{ inputs.pat }}" >> $GITHUB_ENV
          echo "MERGING_PR_NUMBER=${{ inputs.merging_pr_number }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      run: python ./main.py
      shell: bash