# action.yaml
name: 'GitHub Action Checkbox Checker'
description: 'GitHub Action that checks when a PR is merged and edits comments referring to it'
inputs:
  pat:
    description: 'GitHub Personal Access Token to edit comments'
    required: true
  merging_pr_repository:
    description: 'Repository of the PR being merged'
    required: true
  merging_pr_number:
    description: 'Number of the PR being merged'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"